### ISSUE TITLE
anim.py fails with ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by MaromGold** [gumpu/TSP_Animation#1]
SA
Traceback (most recent call last):
  File ".\anim.py", line 595, in <module>
    print solve('problem3.dat')
  File ".\anim.py", line 585, in solve
    solution = create_animation(nodes)
  File ".\anim.py", line 557, in create_animation
    s = sa_algorithm(nodes, number_of_nodes)
  File ".\anim.py", line 357, in sa_algorithm
    solution = sa_optimize_step(nodes, solution, number_of_nodes, t)
  File ".\anim.py", line 287, in sa_optimize_step
    frame(nodes, new_solution, number_of_nodes, t, c, y, x, z, gain)
  File ".\anim.py", line 82, in frame
    plt.title('(4)  SA Temp {:4.1f} Best Tour {:6.1f}\nSwaps {}  Gain {:12.2f} '.format(t,l_min,nn,gain))
ValueError: Unknown format code 'f' for object of type 'str'

**Comment by Eurus-Holmes** [comment]
oh, I have the same error with you...
how to solve it...

**Comment by MaromGold** [comment]
I wish I knew :) That's why I posted this problem in the first place. I was hoping that @gumpu will respond and save us all ;)

**Comment by Eurus-Holmes** [comment]
I know how to run normally...
you can just comment on line 82:
`#plt.title('(4) SA Temp {:4.1f} Best Tour {:6.1f}\nSwaps {} Gain {:12.2f} '.format(t,l_min,nn,gain))`
...
but I still don't know why...
I have generated a file called sa.mp4 to the animation...

**Comment by Eurus-Holmes** [comment]
@MaromGold 
I have solved it!
with 
`plt.title('(4)  SA Temp {} Best Tour {}\nSwaps {}  Gain {} '.format(t, l_min, nn, gain))` 
instead
`plt.title('(4) SA Temp {:4.1f} Best Tour {:6.1f}\nSwaps {} Gain {:12.2f} '.format(t,l_min,nn,gain))`

**Comment by gumpu** [comment]
Problem was that l_min is None in the few first steps of the SA run.  
Added a fix for this.   (Your fix works too but probably will make the title jump around a bit).

**Comment by MaromGold** [comment]
Thanks a lot, @gumpu  :)

**Comment by MaromGold** [comment]
I can't figure out how to make an animation using all of these single files. and "make .anim" doesn't seem to work. What am I doing wrong? :(

**Comment by gumpu** [comment]
You mean `make` does not work.  If you have a ton of single files `make .anim` probably did work.

What error message do you get?

A

    make clean
    make .anim
    make

work on Ubuntu 16.04.  Provided you  have `ffmpeg` installed.

**Comment by MaromGold** [comment]
http://prntscr.com/junwrp

**Comment by gumpu** [comment]
I see the problem `make` has to be run from the command-line, not from within Python.
You can also do it without `make` by executing

    python anim.py
    ffmpeg -r 10 -i %5d.png -vb 20M sa.mp4

But this still has to be done from the command-line.
What OS are you on?

**Comment by MaromGold** [comment]
OS = Windows 10.
Your ffmpeg command worked :) 
Thank you very very much!!
